config/routes.rb
AutoRoster::Application.routes.draw do

  resources :organizations do
    get "calendar" => "calendar#index"
    resources :roles
    resources :schedules
  end

  root :to => 'organizations#empty'

end

app/models/organization.rb
class Organization
  include Mongoid::Document
  embeds_many :users
  has_many :schedules
  field :name, type: String
  field :roles, type: Array
  field :event_requirments, type: Array

end

app/models/schedule.rb
class Schedule
  include Mongoid::Document
  belongs_to :organization
  field :member, type: String
  field :start_time, type: Time
  field :available_for, type: Integer, default: 1
end

app/models/user.rb
class User
  include Mongoid::Document
  has_many :schedules
  field :name, type: String
  field :time_zone, :type => String, :default => "GMT"
  belongs_to :organization
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :set_timezone
  helper_method :current_organization

  def current_organization
    if session[:current_organization].blank?
      session[:current_organization] = Organization.first
    end
    session[:current_organization]
  end

  def set_timezone
    if cookies[:time_zone]
      Time.zone = cookies[:time_zone]
    else
      Time.zone = "GMT"
    end
  end
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  before_filter :set_organization
  def index

  end

  def set_organization
    @organization = Organization.where(id: params[:organization_id]).first
    @organization = Organization.where(name: params[:organization_id]).first if !@organization
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @organizations }
    end
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    @organization = Organization.where(id: params[:id]).first
    @organization = Organization.where(name: params[:id]).first if !@organization

    redirect_to(organization_calendar_path(@organization))
  end

  # GET /organizations/new
  # GET /organizations/new.json
  def new
    @organization = Organization.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/1/edit
  def edit
    @organization = Organization.find(params[:id])
    @organization.roles = @organization.roles.join(", ")
  end

  # POST /organizations
  # POST /organizations.json
  def create

    @organization = Organization.new(params[:organization])
    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render json: @organization, status: :created, location: @organization }
      else
        format.html { render action: "new" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /organizations/1
  # PUT /organizations/1.json
  def update
    params[:organization][:roles] = params[:organization][:roles].split(",").collect{|r| r.strip!;r} if params[:organization][:roles]
    @organization = Organization.find(params[:id])

    respond_to do |format|
      if @organization.update_attributes(params[:organization])
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization = Organization.find(params[:id])
    @organization.destroy

    respond_to do |format|
      format.html { redirect_to organizations_url }
      format.json { head :no_content }
    end
  end

  def empty
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_filter :set_organization

  def set_organization
    @organization = Organization.where(id: params[:organization_id]).first
    @organization = Organization.where(name: params[:organization_id]).first if !@organization
  end
  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = @organization.schedule.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @schedules }
    end
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
    @schedule = Schedule.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @schedule }
    end
  end

  # GET /schedules/new
  # GET /schedules/new.json
  def new
    @schedule = Schedule.new
    @schedule.start_time = Time.zone.now
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @schedule }
    end
  end

  # GET /schedules/1/edit
  def edit
    @schedule = Schedule.find(params[:id])
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = @organization.schedules.new(params[:schedule])
    respond_to do |format|
      if @schedule.save
        format.html { redirect_to organization_calendar_path(@organization), notice: 'Schedule was successfully created.' }
      else
        format.html { render action: "new" }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /schedules/1
  # PUT /schedules/1.json
  def update
    @schedule = Schedule.find(params[:id])

    respond_to do |format|
      if @schedule.update_attributes(params[:schedule])
        format.html { redirect_to organization_calendar_path(@organization), notice: 'Schedule was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy

    respond_to do |format|
      format.html { redirect_to organization_calendar_path(@organization) }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/calendar/index.html.erb
  <div class="row">

    <div class="twelve columns">
      <%=form_tag do%>
        <div class="ten columns">
          <%= time_zone_select :timezone,nil, nil,:default => "GMT"   %>
        </div>
        <div class="twocolumns">
          <%=submit_tag "Switch Time Zone"%>
        </div>
      <%end%>
    </div>

    <div class="twelve columns">
      <table class="twelve">
        <thead>
          <tr>
            <th>
              Member
            </th>
            <% 7.times do |i|%>
            <th><%=(Time.now + i.days).day%> <%=Date::MONTHNAMES[(Time.now + i.days).month]%></th>
            <% end%>
          </tr>
        </thead>
        <tbody>
          <%@organization.schedules.all.collect{|s| s.member}.uniq.each do |m|%>
          <tr>
            <td><%=m%></td>
            <td class="hours" colspan="7">
              <%@organization.schedules.where(:member=>m,:start_time.gt => Time.now.in_time_zone(Time.zone).beginning_of_day, :start_time.lt => Time.now + 7.day ).each do |s|%>
                <div class="schedule"
                  data-start-time="<%=(s.start_time - DateTime.now.in_time_zone(Time.zone).beginning_of_day)/30.minutes%>"
                  data-end-time="<%=s.available_for*2%>"
                  data-tooltip="<%=s.start_time%> to <%=s.start_time + s.available_for.hours%>"></div>
              <%end%>
            </td>
          </tr>
          <%end%>
        </tbody>
      </table>

      <%= link_to 'New Schedule', new_organization_schedule_path(@organization) %>

  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8" />

	<!-- Uncomment to make IE8 render like IE7 -->
	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

	<!-- Set the viewport width to device width for mobile -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

	<!-- Included CSS Files -->
	<%= stylesheet_link_tag    "application" %>

	<!-- Included JS Files  -->
	<%= javascript_include_tag "application" %>

  <%= csrf_meta_tags %>
</head>
<body>

  <!-- Header and Nav -->


  <!-- End Header and Nav -->

  <%= yield %>
</body>
</html>

app/views/organizations/_form.html.erb
<%= simple_form_for(@organization) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :roles %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing organization</h1>

<%= render 'form' %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<div class="row">
  <div class="nine columns">
    <h1>Listing organizations</h1>

    <table class="seven">
      <tr>
        <th>Name</th>
        <th></th>
      </tr>

    <% @organizations.each do |organization| %>
      <tr>
        <td><%= organization.name %></td>
        <td><%= link_to 'View Calendar', organization %></td>
      </tr>
    <% end %>
    </table>

    <br />

    <%#= link_to 'New Organization', new_organization_path %>

  </div>
</div>

app/views/organizations/new.html.erb
<h1>New organization</h1>

<%= render 'form' %>

<%= link_to 'Back', organizations_path %>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @organization.name %>
</p>

<p>
  <b>Roles:</b>
  <%= @organization.roles %>
</p>

<p>
  <b>Users:</b>
  <%= @organization.users %>
</p>


<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>

app/views/roles/edit.html.erb
<h1>Editing role</h1>

<%= simple_form_for(@role,url: organization_role_path(@organization)) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, collection: @organization.roles.sort, :include_blank=>false%>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<%= link_to 'Back', organization_role_path(@organization,@role) %>

app/views/roles/index.html.erb
<h1>Listing Roles for <%=@organization.name%></h1>

<table>
  <tr>
    <th>Role</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @roles.each do |role| %>
  <tr>
    <td><%= role.name %></td>
    <td><%= link_to 'Edit', edit_organization_role_path(@organization,role) %></td>
    <td><%= link_to 'Destroy', organization_role_path(@organization,role), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Role', new_organization_role_path(@organization) %>

app/views/roles/new.html.erb
<h1>New role</h1>

<%= simple_form_for(@role,url: organization_roles_path(@organization)) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, collection: @organization.roles.sort, :include_blank=>false%>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<%= link_to 'Back', organization_roles_path(@organization) %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Start time:</b>
  <%= @role.name %>
</p>

<%= link_to 'Edit', edit_organization_role_path(@role) %> |
<%= link_to 'Back', organization_role_path(@organization,@role) %>

app/views/schedules/_form.html.erb
<%= simple_form_for([@organization,@schedule]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :user, collection: @organization.users.all %>
    <%= f.input :start_time, input_html: {:type=>:datetime}, placeholder: "YYYY-MM-DD HH:MM:SS GMT+X:XX", hint: "You can specify your time zone here. Format YYYY-MM-DD HH:MM:SS GMT+X:XX" %>
    <%= f.input :available_for, :label=> "Hours Available" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<div class="row">
  <div class="nine columns">
    <h1>Editing schedule</h1>

  <%= simple_form_for([@organization,@schedule],url: organization_schedule_url(@organization,@schedule)) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :start_time, input_html: {:type=>:datetime}, placeholder: "YYYY-MM-DD HH:MM:SS GMT+X:XX", hint: "You can specify your time zone here. Format YYYY-MM-DD HH:MM:SS GMT+X:XX" %>
      <%= f.input :available_for, :label=> "Hours Available" %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>

    <%= link_to 'Back', organization_calendar_path(@organization) %>
  </div>
</div>

app/views/schedules/new.html.erb
<div class="row">
  <div class="nine columns">
<h1>New schedule</h1>


  <%= simple_form_for([@organization,@schedule],url: organization_schedules_url(@organization)) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :member %>
      <%= f.input :start_time, input_html: {:type=>:datetime}, placeholder: "YYYY-MM-DD HH:MM:SS GMT+X:XX", hint: "You can specify your time zone here. Format YYYY-MM-DD HH:MM:SS GMT+X:XX" %>
      <%= f.input :available_for, :label=> "Hours Available" %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>


<%= link_to 'Back', organization_calendar_path(@organization)%>
</div>
</div>